"""add balance column to loans

Revision ID: 745a8f99fb7f
Revises: e151feaee9a7
Create Date: 2025-09-03 09:10:46.030791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745a8f99fb7f'
down_revision: Union[str, None] = 'e151feaee9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('disbursements', sa.Column('date', sa.Date(), nullable=True))  # Removed
    op.create_index(op.f('ix_disbursements_id'), 'disbursements', ['id'], unique=False)
    op.add_column('loans', sa.Column('balance', sa.Float(), nullable=True))
    op.alter_column('loans', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.alter_column('loans', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('loans', 'balance')
    op.drop_index(op.f('ix_disbursements_id'), table_name='disbursements')
    op.drop_column('disbursements', 'date')
    # ### end Alembic commands ###
 